### ISSUE TITLE
Failure to get status from cached lv

### ISSUE THREAD

**Issue by AnthonyVH** [larsks/lvcache#7]
lvcache can't read the status from a cached LV. The reason seems to be it does not remove the brackets around the "hidden" LVs used to cache. E.g. I have an LV lv-linux, cached by lv-cache, with cache metadata on lv-cache-meta. This results in the following output for `sudo lvs -a`:

    LV               VG      Attr       LSize  Pool       Origin           Data%  Meta%  Move Log Cpy%Sync Convert
    [lv-cache]       vg-raid Cwi---C--- 55.77g                             100.00 11.09           12.65           
    [lv-cache_cdata] vg-raid Cwi-ao---- 55.77g                                                                    
    [lv-cache_cmeta] vg-raid ewi-ao---- 64.00m                                                                    
    lv-linux         vg-raid Cwi-aoC---  1.79t [lv-cache] [lv-linux_corig] 100.00 11.09           12.65           
    [lv-linux_corig] vg-raid owi-aoC---  1.79t                                                                    
    [lvol0_pmspare]  vg-raid ewi------- 64.00m                                                                    

When lvcache attempts to get the status of any of the hidden LVs (those in brackets), it does not strip the brackets and `lvs` outputs an error, i.e.: 

    RAN: '/sbin/lvs --noheadings --unbuffered --nosuffix --units b -o lv_size vg-raid/[lv-cache]'
    STDOUT:
    STDERR:
    Failed to find logical volume "vg-raid/[lv-cache]"

Removing the brackets from the function call solves the problem.

**Comment by larsks** [comment]
This was fixed in #9.
